[package]
name = "hascan"
version = "0.1.0"
edition = "2021"



[dependencies]
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "sync", "time", "io-util", "net", "macros"] }
axum = "0.7.5"
serde = "1.0.199"
serde_json = "1.0.116"
rusqlite = "0.32.1"
# hacash = { git = "https://github.com/hacash/fullnode", package = "hacash"}
hacash = { path = "../fullnode", package = "hacash", default-features = false }
sys = { path = "../fullnode/sys" }
field = { path = "../fullnode/field" }
# db = { path = "../fullnode/db" }
protocol = { path = "../fullnode/protocol"}
mint = { path = "../fullnode/mint" }
node = { path = "../fullnode/node" }
chain = { path = "../fullnode/chain"}
server = { path = "../fullnode/server" }

[features]
default = ["db-leveldb-sys"]
db-sled = ["hacash/db-sled"]
db-rusty-leveldb = ["hacash/db-rusty-leveldb"]
db-leveldb-sys = ["hacash/db-leveldb-sys"]

# [profile.release]
# opt-level = 3       # Optimize for size.
# lto = true          # Enable Link Time Optimization
# codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# panic = 'abort'     # Abort on panic
# strip = true        # Strip symbols from binary

