[package]
name = "hascan"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.116"
rusqlite = "0.32.1"
app = { path = "../fullnode/app", default-features = false }
sys = { path = "../fullnode/sys" }
field = { path = "../fullnode/field" }
base = { path = "../fullnode/base" }
protocol = { path = "../fullnode/protocol" }
mint = { path = "../fullnode/mint" }
vm = { path = "../fullnode/vm" }

[features]
default = ["db-leveldb-sys"]
db-sled = ["app/db-sled"]
db-rusty-leveldb = ["app/db-rusty-leveldb"]
db-leveldb-sys = ["app/db-leveldb-sys"]
db-rocksdb = ["app/db-rocksdb"]

# [profile.release]
# opt-level = 3       # Optimize for size.
# lto = true          # Enable Link Time Optimization
# codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# panic = 'abort'     # Abort on panic
# strip = true        # Strip symbols from binary
